### ISSUE TITLE
Cross section doesn't work when dofit + doeff are disabled

### ISSUE THREAD

**Issue by lvermunt** [ginnocen/MachineLearningHEP#407]
When the full analysis chain is enabled (so fit by loading AliHFInvMassFitter, efficiency with the python code, and cross section by loading HFPtSpectrum) everything runs smoothly. When only docross is enabled, the package crashes after processing the first period with the following message:

``` *** Break *** segmentation violation
Traceback (most recent call last):
  File "do_entire_analysis.py", line 23, in <module>
    main()
  File "/home/lvermunt/JulyALICE/fork/MachineLearningHEP/machine_learning_hep/steer_analysis.py", line 461, in main
    do_entire_analysis(run_config, db_analysis, db_ml_models, db_ml_gridsearch, db_run_list)
  File "/home/lvermunt/JulyALICE/fork/MachineLearningHEP/machine_learning_hep/steer_analysis.py", line 390, in do_entire_analysis
    myan.multi_makenormyields()
  File "/home/lvermunt/JulyALICE/fork/MachineLearningHEP/machine_learning_hep/multianalyzer.py", line 113, in multi_makenormyields
    self.process_listsample[indexp].makenormyields()
  File "/home/lvermunt/JulyALICE/fork/MachineLearningHEP/machine_learning_hep/analyzer.py", line 1513, in makenormyields
    gROOT.LoadMacro("HFPtSpectrum.C")
SystemError: int TROOT::LoadMacro(const char* filename, int* error = 0, bool check = kFALSE) =>
    problem in C++; program state has been reset

 *** Break *** segmentation violation
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/cvmfs/alice.cern.ch/el6-x86_64/Packages/ROOT/v6-16-00-18/lib/ROOT.py", line 770, in cleanup
    isCocoa = _root.gSystem.InheritsFrom( 'TMacOSXSystem' )
TypeError: none of the 2 overloaded methods succeeded. Full details:
  bool TObject::InheritsFrom(const char* classname) =>
    problem in C++; program state has been reset
  bool TObject::InheritsFrom(const TClass* cl) =>
    could not convert argument 1

 *** Break *** segmentation violation
Segmentation fault (core dumped)
```

I don't see what can cause this. @benedikt-voelkel, do you have an idea? For plot_multi_trial you are also loading a .C macro. Does this work stand-alone?

**Comment by ginnocen** [comment]
Hi both, let me know if you have pb figuring this out. I can have a look as well later today if needed.

**Comment by benedikt-voelkel** [comment]
@lvermunt Is this somehow still an issue? I just saw that (it's very old, sorry...) Otherwise we can close it?!

**Comment by lvermunt** [comment]
I didn't notice it anymore, but this can also be because I was used to enabling all flags. For me it is fine to close. We can always (re)open another issue if needed
